spring:
  application:
    name: delivery-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/orders
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group

server:
  port: 8080

payment-service:
  base-url: http://localhost:8081/api/payments

order-paid-topic: orders.events
delivery-topic: delivery.events